---
maven-params: &maven-params
  MAVEN_OPTS: {{maven-opts}}
  MAVEN_CONFIG: {{maven-config}}

cf-params: &cf-params
  CF_API_URL: {{cf-api-url}}
  CF_SKIP_SSL: {{cf-skip-ssl}}
  CF_USERNAME: {{cf-username}}
  CF_PASSWORD: {{cf-password}}
  CF_ORG: {{cf-org}}
  CF_SPACE: {{cf-space}}
  CF_APP_NAME: {{cf-app-name}}
  CF_APP_HOST: {{cf-app-host}}

jobs:
- name: unit-test
  public: true
  plan:
  - get: pcfdemo
    trigger: true
  - task: unit
    file: pcfdemo/ci/tasks/unit.yml
    params:
      <<: *maven-params

- name: build-artifact
  serial_groups: [ version ]
  plan:
  - get: pcfdemo
    passed: [ unit-test ]
    trigger: true
  - get: version
    params: { pre: rc }
  - task: build
    file: pcfdemo/ci/tasks/build.yml
    params:
      <<: *maven-params
  - put: candidate-release
    params: { file: build-output/pcf-demo-*.war }
  - put: version
    params: { file: version/number }

- name: integration-test
  serial: true
  plan:
  - get: candidate-release
    trigger: true
    passed: [ build-artifact ]
  - get: pcfdemo
    passed: [ build-artifact ]
  - get: version
    passed: [ build-artifact ]
  #- task: prepare-cf
   # file: pcfdemo/ci/tasks/prepare-cf.yml
   # params:
   #   <<: *cf-params
  - put: cf
    params:
      manifest: prepare-cf-output/manifest.yml
  - task: integration
    file: pcfdemo/ci/tasks/integration.yml
    params:
      <<: *maven-params

- name: ship-it
  serial_groups: [ version ]
  plan:
  - get: candidate-release
    passed: [ integration-test ]
  - get: pcfdemo
    passed: [ integration-test ]
  - get: version
    params: { bump: final }
  - task: prepare-final
    file: pcfdemo/ci/tasks/prepare-final.yml
  - put: final-release
    params: { file: prepare-final-output/pcf-demo-*.war }
  - put: version
    params: { file: version/number }

- name: major
  serial_groups: [ version ]
  plan:
  - put: version
    params: { bump: major, pre: rc }

- name: minor
  serial_groups: [ version ]
  plan:
  - put: version
    params: { bump: minor, pre: rc }

- name: patch
  serial_groups: [ version ]
  plan:
  - get: version
    passed: [ ship-it ]
    trigger: true
  - put: version
    params: { bump: patch, pre: rc }

resources:
- name: pcfdemo
  type: git
  source:
    uri: {{github-uri}}
    branch: {{github-branch}}

- name: version
  type: semver
  source:
    bucket: {{s3-bucket-version}}
    initial_version: 1.0.0-rc.0
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

- name: candidate-release
  type: s3
  source:
    bucket: {{s3-bucket-release-candidates}}
    regexp: pcf-demo-(.*).war
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

- name: final-release
  type: s3
  source:
    bucket: {{s3-bucket-releases}}
    regexp: pcf-demo-(.*).war
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

- name: cf
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true
